---
- name: Deploy Petclinic App
  hosts: webserver
  become: yes

  tasks:
    - name: Create app directory
      file:
        path: /app
        state: directory

    - name: Copy Petclinic jar
      copy:
        src: target/spring-petclinic-2.5.0.jar
        dest: /app/petclinic.jar

    - name: Install systemd service
      template:
        src: petclinic.service.j2
        dest: /etc/systemd/system/petclinic.service
      notify:
        - Reload systemd
        - Restart petclinic

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart petclinic
      systemd:
        name: petclinic
        state: restarted
