- name: Deploy Petclinic App
  hosts: 172.16.238.11
  become: yes
  remote_user: root

  tasks:
    - name: Create app directory
      file:
        path: /app
        state: directory

    - name: Copy Petclinic jar
      copy:
        src: "{{ jar_file }}"
        dest: /app/petclinic.jar

    - name: Run Petclinic application
      shell: "nohup java -jar /app/petclinic.jar &"
      args:
        executable: /bin/bash
      async: 1
      poll: 0
