- name: Deploy Petclinic App
  hosts: 172.16.238.11
  become: yes
  remote_user: root

  tasks:
    - name: Create app directory
      file:
        path: /app
        state: directory

    - name: Copy Petclinic jar
      copy:
        src: "{{ workspace }}/target/spring-petclinic-*.jar"
        dest: /app/petclinic.jar

    - name: Install systemd service
      template:
        src: petclinic.service.j2
        dest: /etc/systemd/system/petclinic.service
      notify:
        - Reload systemd
        - Restart petclinic

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart petclinic
      systemd:
        name: petclinic
        state: restarted
